# Generated by Django 5.1.3 on 2024-12-05 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=150)),
                ('category_type', models.CharField(choices=[('HEALTH', 'HEALTH'), ('EDUCATION', 'EDUCATION'), ('TECHNOLOGY', 'TECHNOLOGY')], max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('approval_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], max_length=17)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
