# Generated by Django 5.1.3 on 2024-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
