# Generated by Django 5.1.3 on 2024-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaignpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ManyToManyField(blank=True, to='campaign.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
