# Generated by Django 5.1.3 on 2024-12-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaign_category_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='current_funding',
        ),
    ]
