# Generated by Django 5.1.3 on 2024-12-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_remove_campaign_current_funding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='category',
            new_name='categories',
        ),
    ]
