# Generated by Django 5.1.3 on 2024-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_donated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
