# Generated by Django 5.1.3 on 2024-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='back_cover',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='front_cover',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='personal-profile'),
        ),
    ]
